/**
 * Tema de Tailwind alineado con las tokens de `src/estilos/global.css`.
 * Cada clave apunta a `var(--...)` para no duplicar valores literales.
 */

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        red: {
          50: 'var(--color-red-50)',
          100: 'var(--color-red-100)',
          200: 'var(--color-red-200)',
          300: 'var(--color-red-300)',
          400: 'var(--color-red-400)',
          500: 'var(--color-red-500)',
          600: 'var(--color-red-600)',
          700: 'var(--color-red-700)',
          800: 'var(--color-red-800)',
          900: 'var(--color-red-900)',
        },
        'red-wine': {
          50: 'var(--color-red-wine-50)',
          100: 'var(--color-red-wine-100)',
          200: 'var(--color-red-wine-200)',
          300: 'var(--color-red-wine-300)',
          400: 'var(--color-red-wine-400)',
          500: 'var(--color-red-wine-500)',
          600: 'var(--color-red-wine-600)',
          700: 'var(--color-red-wine-700)',
          800: 'var(--color-red-wine-800)',
          900: 'var(--color-red-wine-900)',
        },
        school: {
          business: 'var(--color-school-business)',
          'computer-science': 'var(--color-school-computer-science)',
          health: 'var(--color-school-health)',
          education: 'var(--color-school-education)',
          'language-institute': 'var(--color-school-language-institute)',
        },
        neutral: {
          50: 'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
          background: 'var(--color-neutral-background)',
          primary: 'var(--color-neutral-primary)',
        },
        alert: {
          destructive: {
            bg: 'var(--color-alert-destructive-bg)',
            light: 'var(--color-alert-destructive-light)',
            darker: 'var(--color-alert-destructive-darker)',
          },
          error: 'var(--color-alert-error)',
          accent: 'var(--color-alert-accent)',
          'accent-2': 'var(--color-alert-accent-2)',
          warning: 'var(--color-alert-warning)',
          primary: 'var(--color-alert-primary)',
          'accent-3': 'var(--color-alert-accent-3)',
        },
        primary: {
          50: 'var(--color-primary-50)',
          500: 'var(--color-primary-500)',
          700: 'var(--color-primary-700)',
          900: 'var(--color-primary-900)',
        },
        accent: {
          secondary: 'var(--color-accent-secondary)',
        },
        bg: {
          light: 'var(--color-bg-light)',
          dark: 'var(--color-bg-dark)',
        },
        web: {
          white: 'var(--color-web-white)',
          black: 'var(--color-web-black)',
        },
        black: 'var(--color-black)',
        white: 'var(--color-white)',
      },
      fontFamily: {
        primary: 'var(--font-family-primary)',
        secondary: 'var(--font-family-secondary)',
      },
      fontSize: {
        xs: 'var(--font-size-xs)',
        sm: 'var(--font-size-sm)',
        md: 'var(--font-size-md)',
        lg: 'var(--font-size-lg)',
        xl: 'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
        '3xl': 'var(--font-size-3xl)',
        '4xl': 'var(--font-size-4xl)',
        '5xl': 'var(--font-size-5xl)',
        'mb-xs': 'var(--fontsize-mb-xs)',
        'mb-sm': 'var(--fontsize-mb-sm)',
        'mb-md': 'var(--fontsize-mb-md)',
        'mb-lg': 'var(--fontsize-mb-lg)',
        'mb-xl': 'var(--fontsize-mb-xl)',
        'mb-xxl': 'var(--fontsize-mb-xxl)',
        'mb-xxxl': 'var(--fontsize-mb-xxxl)',
        'mb-xxxxl': 'var(--fontsize-mb-xxxxl)',
        'mb-xxxxxl': 'var(--fontsize-mb-xxxxxl)',
      },
      spacing: {
        '4xs': 'var(--gap-4xs)',
        '3xs': 'var(--gap-3xs)',
        '2xs': 'var(--gap-2xs)',
        xs: 'var(--gap-xs)',
        sm: 'var(--gap-sm)',
        md: 'var(--gap-md)',
        lg: 'var(--gap-lg)',
        xl: 'var(--gap-xl)',
        '2xl': 'var(--gap-2xl)',
        '3xl': 'var(--gap-3xl)',
        '4xl': 'var(--gap-4xl)',
        xxxxs: 'var(--gap-xxxxs)',
        xxxs: 'var(--gap-xxxs)',
        xxs: 'var(--gap-xxs)',
        xxl: 'var(--gap-xxl)',
        xxxl: 'var(--gap-xxxl)',
        xxxxl: 'var(--gap-xxxxl)',
      },
      borderWidth: {
        xs: 'var(--border-width-xs)',
        sm: 'var(--border-width-sm)',
        md: 'var(--border-width-md)',
        lg: 'var(--border-width-lg)',
      },
      borderRadius: {
        '2xs': 'var(--radius-2xs)',
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
        'xxs-bd': 'var(--radius-xxs-bd)',
        'xs-bd': 'var(--radius-xs-bd)',
        'sm-bd': 'var(--radius-sm-bd)',
        'md-bd': 'var(--radius-md-bd)',
        'lg-bd': 'var(--radius-lg-bd)',
        'xl-bd': 'var(--radius-xl-bd)',
        'xxl-bd': 'var(--radius-xxl-bd)',
      },
      boxShadow: {
        'soft-natural': 'var(--shadow-soft-natural)',
        'hard-black': 'var(--shadow-hard-black)',
      },
    },
  },
};
